app = 'learnify-autumn-field-7370'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 80  # غيرنا من 80 إلى 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
