# fly.toml app configuration file generated for learnify-autumn-field-7370 on 2025-07-18T13:57:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'learnify-autumn-field-7370'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
